### PR TITLE
chore: set up semantic-release

### PR DESCRIPTION
**Pull request by fernandoespinosa**
These changes and the execution of **semantic-release** were tested as follows:

1. A temporary release branch named `release-branch` in the forked repo was used as the source of releases. However this PR makes `master` the final release branch.

   * This branch was made protected and updated though the regular process of Pull Request on GitHub.
   * These PRs contained simple changes with conventional-commit messages as enforced by `commitlint` (see previous #1).

image

2. Sample link to PR included in a release: https://github.com/fernandoespinosa/polymath-sdk/pull/5

image

3. The actual **semantic-release** was triggered upon PR merge onto the `release-branch` from a temporary local CI environment (TeamCity running on Docker).

4. The actual publishing was made to the temporary testing npm account **fernando.polymath.network**

image

5. The final effects of the successful release look like this:
image

### CODE REVIEW

**Comment by RafaelVidaurre** [comment]
Looking good! the next step would be then to setup travis to do this, right?

**Comment by RafaelVidaurre** [comment]
Also, it seems like we will want to have beta releases as well on a `next` branch.

**Comment by fernandoespinosa** [comment]
@RafaelVidaurre - exactly, next step will be to configure the CI build/release process. I will also look into beta releases and a `next` branch...

**Pull request merged**
